
	<ul class="nav flex-column well">
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Menu de test</li>
          <li><a class="nav-link" href="<?= WEB_ROOT; ?>/rechercher"><span class="oi oi-reload iconeMenu"></span>Affiche Index Recherche</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter"><span class="oi oi-eye iconeMenu"></span>Consultation</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/"><span class="oi oi-eye iconeMenu"></span>Consulter liste des profile</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/tous"><span class="oi oi-eye iconeMenu"></span>Consulter tous les profile</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/offres/"><span class="oi oi-eye iconeMenu"></span>Consulter les offres</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/de/4565_789"><span class="oi oi-eye iconeMenu"></span>Consulter un profile</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/de/121351-RTGDF"><span class="oi oi-eye iconeMenu"></span>Consulter profile 12321354</a></li>
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><span class="oi oi-eye iconeMenu"></span>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><span class="oi oi-bug iconeMenu"></span>Erreur</a></li>
     </ul>

