<form class="was-validated">
  <div class="custom-control custom-checkbox mb-3">
    <input type="checkbox" class="custom-control-input" id="customControlValidation1" checked required>
    <label class="custom-control-label" for="customControlValidation1">Afficher la zone</label>
    <div class="invalid-feedback">Affichage de zone Caché</div>
  </div>

  <div class="custom-control custom-radio">
    <input type="radio" class="custom-control-input" id="customControlValidation2" name="radio-stacked" required>
    <label class="custom-control-label" for="customControlValidation2">Diplômé</label>
  </div>
	<div class="custom-control custom-radio">
    <input type="radio" class="custom-control-input" id="customControlValidation3" name="radio-stacked" required>
    <label class="custom-control-label" for="customControlValidation3">Stagiaire</label>
  </div>
  <div class="custom-control custom-radio mb-3">
    <input type="radio" class="custom-control-input" id="customControlValidation4" name="radio-stacked" required>
    <label class="custom-control-label" for="customControlValidation4">Non Diplômé</label>
  </div>
  <div class="custom-control custom-text">
    <label for="customRange">Distance</label>
  	<input type="range" class="custom-range" id="customRange" name="points1">
  </div>
</form>
