
	<ul class="nav flex-column well">
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Menu de test</li>
          <li><a class="nav-link" href="<?= WEB_ROOT; ?>/rechercher"><span class="oi oi-reload iconeMenu"></span>Affiche Index Recherche</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/map"><span class="oi oi-map-marker iconeMenu"></span>map</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/distance"><span class="oi oi-signpost iconeMenu"></span>distances</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/candidature/"><span class="oi oi-plus iconeMenu"></span>Poster une candidature</a></li>
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><span class="oi oi-eye iconeMenu"></span>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><span class="oi oi-bug iconeMenu"></span>Erreur</a></li>
     </ul>
