
	<ul class="nav flex-column well">
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Menu de test</li>
          <li><a class="nav-link" href="<?= WEB_ROOT; ?>/rechercher"><i class="fas fa-home iconeMenu"></i>Affiche Index Recherche</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/map"><i class="fas fa-map-marker-alt iconeMenu"></i>map</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/distance"><i class="fas fa-route iconeMenu"></i>distances</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/candidature"><i class="fas fa-portrait iconeMenu"></i>Candidature</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/rechercher/structure"><i class="fas fa-map-marked-alt iconeMenu"></i>Structure</a></li>
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><i class="fas fa-eye iconeMenu"></i>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><i class="fas fa-bug iconeMenu"></i>Erreur</a></li>
     </ul>
