
	<ul class="nav flex-column well">
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Menu de test</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter"><i class="fas fa-home iconeMenu"></i>Affiche Index Consulter</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter"><i class="fas fa-eye iconeMenu"></i>Consultation</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/"><i class="fas fa-eye iconeMenu"></i>Consulter liste des profile</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/tous"><i class="fas fa-eye iconeMenu"></i>Consulter tous les profile</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/offres/"><i class="fas fa-eye iconeMenu"></i>Consulter les offres</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/de/4565_789"><i class="fas fa-eye iconeMenu"></i>Consulter un profile</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/profiles/de/121351-RTGDF"><i class="fas fa-eye iconeMenu"></i>Consulter profile 12321354</a></li>
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><i class="fas fa-eye iconeMenu"></i>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><i class="fas fa-bug iconeMenu"></i>Erreur</a></li>
     </ul>

