
	<ul class="nav flex-column well">
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Menu de test</li>
          <li><a class="nav-link" href="<?= WEB_ROOT; ?>/poster"><i class="fas fa-home iconeMenu"></i>Affiche Index Recherche</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/offre/"><i class="fas fa-plus iconeMenu"></i>Poster une Offre</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/candidature/"><i class="fas fa-plus iconeMenu"></i>Poster une candidature</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/document/"><i class="fas fa-plus iconeMenu"></i>Poster un document</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/evenement/"><i class="fas fa-plus iconeMenu"></i>Poster un évenement</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/formation/"><i class="fas fa-plus iconeMenu"></i>Poster une formation</a></li>
          <li class="nav-header"><i class="fas fa-chevron-right iconeMenu"></i>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><i class="fas fa-eye iconeMenu"></i>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><i class="fas fa-bug iconeMenu"></i>Erreur</a></li>
     </ul>
