
	<ul class="nav flex-column well">
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Menu de test</li>
          <li><a class="nav-link" href="<?= WEB_ROOT; ?>/poster"><span class="oi oi-reload iconeMenu"></span>Affiche Index Poster</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/offre/"><span class="oi oi-plus iconeMenu"></span>Poster une Offre</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/candidature/"><span class="oi oi-plus iconeMenu"></span>Poster une candidature</a></li>
		  <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/document/"><span class="oi oi-plus iconeMenu"></span>Poster un document</a></li>
		<li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/evenement/"><span class="oi oi-plus iconeMenu"></span>Poster un évenement</a></li>
		<li><a class="nav-link"  href="<?= WEB_ROOT; ?>/poster/formation/"><span class="oi oi-plus iconeMenu"></span>Poster une formation</a></li>
          <li class="nav-header"><span class="oi oi-chevron-right iconeMenu"></span>Autres :</li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulter/toto/"><span class="oi oi-eye iconeMenu"></span>voire toto</a></li>
          <li><a class="nav-link"  href="<?= WEB_ROOT; ?>/consulterd"><span class="oi oi-bug iconeMenu"></span>Erreur</a></li>
     </ul>
